### ISSUE TITLE
CID Ca

### ISSUE THREAD

**Issue by yozgatliahmed** [raburton/evoplus_cid#13]

**Comment by yozgatliahmed** [comment]
After I changed the CID I get a confirmation. However, it doesn't fully take over.

Example:

I want this CID Number:
0941504d494253540219f007b7011800
But this is assumed:
0941504d494253540219f007b701187f

Another CID
0941504d49425354021a204ef9015600
Same problem:
0941504d49425354021a204ef90156bf

**Comment by raburton** [comment]
It's unlikely you do want 00 on the end. This is the checksum and is rarely actually 00, but some systems don't bother to read/recalculate them, and just display 00.

**Comment by yozgatliahmed** [comment]
Same problem:
0941504d4942535402198035ac011701
0941504d4942535402198035ac0117c3

**Comment by yozgatliahmed** [comment]
> It's unlikely you do want 00 on the end. This is the checksum and is rarely actually 00, but some systems don't bother to read/recalculate them, and just display 00.

How can i fix this Problem?

**Comment by raburton** [comment]
If you are asking for ...15600 and it's actually being set to ...156bf then it looks like the checksum is being recalculated. I can't check it's correct as I don't have a computer here I can run the code on, but no reason to think it isn't. So I don't think there is any problem.

**Comment by raburton** [comment]
I've checked these checksums for you, the ones that have been set are correct.

**Comment by yozgatliahmed** [comment]
Its function. Thx.
