### ISSUE TITLE
Mac OS binary

### ISSUE THREAD

**Issue by Commifreak** [raburton/evoplus_cid#2]
Hi,

how to build under Mac OS (if possible)?

**Comment by raburton** [comment]
No idea if it would work on a mac. I assume if you have gcc available you can just do `gcc -o evoplus_cid evoplus_cid.c` in the jni folder to try to compile it, but it may need tweaking or may not work at all.

**Comment by matbard** [comment]
Hi,

I tried to compile evocid under Ubuntu but received errors. The changed CID on my Samsung Evoplus 32 GB shows Always "01" as the last two characters, no matter on which PC I use(I have two).

**Comment by raburton** [comment]
@matbard  this issue is about osx compiling, please open a different issue

**Comment by matbard** [comment]
Under OSX the GCC compiler finds the Linux/types.h header missing

**Comment by Commifreak** [comment]
Indeed, but when I add these types manually, it compiles with warnings. The binary answers me but it seems that it does not work at all. Hint: Unmount the card before using! After using the card mount itself again.

Gruß,
R. Kluth

**Comment by Tetonne** [comment]
To be able to compile on MacOS i need to replace

#include <linux/types.h>
in /jni/ioctl.h with:

#ifdef __linux__
# include "linux/types.h"
#else
# include <stdint.h>
typedef uint64_t __u64;
typedef uint32_t __u32;
typedef int32_t __s32;
typedef uint16_t __u16;
typedef uint8_t __u8;
#endif

This info was Found here
