### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by MikePryadko** [raburton/evoplus_cid#6]
For compile under *pure* linux (NOT Android) is needed three additional includes:
`#include <string.h>`
`#include <stdlib.h>`
`#include <unistd.h>`

**Comment by kYroL01** [comment]
https://github.com/raburton/evoplus_cid/pull/8 hope he can merge to fix it

**Comment by kYroL01** [comment]
Why this issue is closed even if the bug is still present ? I sent a PR to fix this

**Comment by raburton** [comment]
It's not a bug, this code is for Android, although it's easy enough to compile it for regular Linux if you want to. I don't seem to have been notified about your PR, but having just looked at it is is full of other unrelated changes so it won't be accepted as is. Also, do the additional include files cause any problem with compiled for Android? Would need to make sure it doesn't break existing, intended platform before accepting.

**Comment by kYroL01** [comment]
Ok @raburton i got the point.
Actually I don't see how adding standard C libraries in C code can cause problems, but ok, u need to be sure about it.
But, for example, use `void main {.... return; }` is not good C coding. This is why I changed in `int main { ... return 0; }`, and this is C code that does not affect the Android world.

Thanks for the reply

**Comment by raburton** [comment]
You're probably right, but I don't have an android development system setup to test with these days. So I'd need anyone submitting a patch to be able to say that it doesn't break anything, and I'd be happy to take their assurance on this if they did.
